# Generated by Django 3.1.3 on 2020-11-29 08:06

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('myprorate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('url', models.URLField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=200)),
                ('photo', pyuploadcare.dj.models.ImageField()),
                
            ],
        ),
    ]
