# Generated by Django 3.1.3 on 2020-11-29 11:53

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('myprorate', '0003_auto_20201129_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
